export {
  CMS_TRUST_NOTICE,
  aaStandardsCopy,
  aaStandardsSections,
  aboutCopy,
  aboutCustomerExperience,
  aboutStory,
  aboutWhatWeDo,
  contactCopy,
  deliveryCopy,
  deliverySections,
  howItWorksCopy,
  howItWorksSteps,
  preparationCopy,
  preparationSections,
  reviewsCopy,
  statusDisclosureCopy,
  whatToExpectCopy,
  whatToExpectSections,
} from "./content";
